# -*- coding: utf-8 -*-
"""Convert the two brand families to woff2 for the web package.

Kanit is installed per-user on this machine (Google Fonts, OFL); Noto Sans Thai
already lives in fonts/ (googlefonts build - the one that carries Latin glyphs).
Both are OFL, so self-hosting is allowed; the licence text ships alongside.
"""
import os, shutil, sys
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
USER_FONTS = os.path.join(os.environ["LOCALAPPDATA"], "Microsoft", "Windows", "Fonts")
REPO_FONTS = os.path.join(ROOT, "fonts")
OUT = os.path.join(ROOT, "web", "src", "fonts")   # next to styles.css so ./fonts/ resolves

WEIGHTS = [("Light", 300), ("Regular", 400), ("Medium", 500),
           ("SemiBold", 600), ("Bold", 700)]

FAMILIES = [
    ("Kanit", USER_FONTS, "Kanit-%s.ttf"),
    ("Noto Sans Thai", REPO_FONTS, "NotoSansThai-%s.ttf"),
]


def to_woff2(src, dst):
    f = TTFont(src)
    f.flavor = "woff2"
    f.save(dst)
    return os.path.getsize(dst)


def main():
    os.makedirs(OUT, exist_ok=True)
    faces, missing = [], []
    for family, srcdir, pattern in FAMILIES:
        for style, weight in WEIGHTS:
            src = os.path.join(srcdir, pattern % style)
            if not os.path.exists(src):
                missing.append(src)
                continue
            base = os.path.splitext(pattern % style)[0]
            dst = os.path.join(OUT, base + ".woff2")
            size = to_woff2(src, dst)
            faces.append((family, weight, base + ".woff2", size))
            print("  %-28s %3d  %6.1f KB" % (family, weight, size / 1024))

    if missing:
        print("MISSING:")
        for m in missing:
            print("  " + m)
        sys.exit(1)

    css = ["/* Generated by scripts/build_webfonts.py - do not edit.",
           "   Kanit and Noto Sans Thai are both SIL OFL 1.1; see fonts/OFL-*.txt. */"]
    for family, weight, fname, _ in faces:
        css.append("@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                   "font-display:swap;src:url('./fonts/%s') format('woff2');}"
                   % (family, weight, fname))
    with open(os.path.join(ROOT, "web", "src", "fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(css) + "\n")

    for lic in ("OFL-NotoSansThai.txt",):
        shutil.copy(os.path.join(REPO_FONTS, lic), os.path.join(OUT, lic))
    print("\n%d faces -> web/fonts/, @font-face -> web/src/fonts.css" % len(faces))


if __name__ == "__main__":
    main()
