# -*- coding: utf-8 -*-
"""Embed the NCT marks and the stock photography as data URIs in web/src/assets.ts.

Artifacts render under a CSP that blocks external images, so anything a layout
shows has to travel inside the bundle. The marks are downscaled to the largest
size the layouts actually use (logo 2.56in wide, mark 0.30in) at 2x for retina,
then quantised; the photographs are already cropped and compressed by
scripts/prepare_images.py and are passed through as-is.

Only the photographs a layout or the demo actually shows are inlined - the rest
of assets/ stays on disk for the .potx side, which reads files, not base64.
"""
import base64, io, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "web", "src", "assets.ts")

# name -> (source file, target width in px @2x, has soft gradient?)
ITEMS = [
    ("logoColor", "nct-logo-color.png", 512, True),
    ("logoWhite", "nct-logo-white.png", 512, False),
    ("markColor", "nct-mark-color.png", 180, True),
    ("markWhite", "nct-mark-white.png", 180, False),
]

# name -> source file. Already sized by scripts/prepare_images.py; inlined verbatim.
PHOTOS = [
    ("photoSection", "photo-section.jpg", "image/jpeg"),
    ("photoFacade", "photo-facade.jpg", "image/jpeg"),
    ("photoTower", "photo-tower.jpg", "image/jpeg"),
    ("photoHandshake", "photo-handshake.jpg", "image/jpeg"),
    ("mascot", "mascot.png", "image/png"),
]


def encode(path, width, gradient):
    im = Image.open(path).convert("RGBA")
    h = round(im.height * width / im.width)
    im = im.resize((width, h), Image.LANCZOS)
    # RGBA input -> FASTOCTREE is the only quantiser Pillow allows here
    im = im.quantize(colors=64 if gradient else 16,
                     method=Image.FASTOCTREE).convert("RGBA")
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii"), im.size, len(buf.getvalue())


lines = ["// Generated by scripts/emit_web_assets.py - do not edit.",
         "// NCT marks inlined as data URIs (artifact CSP blocks external images).", ""]
total = 0
for name, fname, w, grad in ITEMS:
    b64, size, raw = encode(os.path.join(SRC, fname), w, grad)
    total += len(b64)
    lines.append("/** %s - %dx%d, %.1f KB */" % (fname, size[0], size[1], raw / 1024))
    # `: string` stops TS inferring a literal type - without it tsup copies the
    # whole base64 blob into index.d.ts as well as index.js
    lines.append("export const %s: string = 'data:image/png;base64,%s';" % (name, b64))
    lines.append("")
    print("  %-11s %4dx%-4d %7.1f KB raw" % (name, size[0], size[1], raw / 1024))

for name, fname, mime in PHOTOS:
    raw = open(os.path.join(SRC, fname), "rb").read()
    b64 = base64.b64encode(raw).decode("ascii")
    total += len(b64)
    size = Image.open(os.path.join(SRC, fname)).size
    lines.append("/** %s - %dx%d, %.1f KB */" % (fname, size[0], size[1], len(raw) / 1024))
    lines.append("export const %s: string = 'data:%s;base64,%s';" % (name, mime, b64))
    lines.append("")
    print("  %-11s %4dx%-4d %7.1f KB raw" % (name, size[0], size[1], len(raw) / 1024))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("\nweb/src/assets.ts  %.1f KB of base64" % (total / 1024))
