# -*- coding: utf-8 -*-
"""Embed the NCT marks and the stock photography as data URIs in web/src/assets.ts.

Artifacts render under a CSP that blocks external images, so anything a layout
shows has to travel inside the bundle. The photographs stay in the main entry on
purpose: design-sync builds the `NctSlides` global from it, and a design agent
working under that CSP has no other way to reach them. A consumer with a bundler
drops the unused ones - package.json marks the JS side-effect free. (Moving them
to a `@nct/slides/photos` entry was tried and reverted for exactly this reason.)

The logos ship at full source width. They used to be cut to 512px "at 2x for
the 2.56in the layouts use" - but the corp cover draws the lockup at 4.375in,
and <Slide fit> scales the whole canvas up to the screen, so a 1920px projector
put 630 css px of logo on a 512px bitmap. 733px is every pixel assets/ has; a
vector master is the real fix and there is none in the repo. The photographs
are already cropped and compressed by scripts/prepare_images.py and pass
through as-is.
"""
import base64, io, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "web", "src", "assets.ts")

# name -> (source file, target width in px, has soft gradient?). None = source width.
ITEMS = [
    ("logoColor", "nct-logo-color.png", None, True),
    ("logoWhite", "nct-logo-white.png", None, False),
    ("markColor", "nct-mark-color.png", 180, True),
    ("markWhite", "nct-mark-white.png", 180, False),
]

# name -> source file. Already sized by scripts/prepare_images.py; inlined verbatim.
PHOTOS = [
    ("photoSection", "photo-section.jpg", "image/jpeg"),
    ("photoFacade", "photo-facade.jpg", "image/jpeg"),
    ("photoTower", "photo-tower.jpg", "image/jpeg"),
    ("photoHandshake", "photo-handshake.jpg", "image/jpeg"),
    ("mascot", "mascot.png", "image/png"),
]


def encode(path, width, gradient):
    im = Image.open(path).convert("RGBA")
    if width and width < im.width:
        im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    # RGBA input -> FASTOCTREE is the only quantiser Pillow allows here. 64 levels
    # banded the gradient lockup once it was drawn larger than its bitmap.
    im = im.quantize(colors=256 if gradient else 16,
                     method=Image.FASTOCTREE).convert("RGBA")
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii"), im.size, len(buf.getvalue())


lines = ["// Generated by scripts/emit_web_assets.py - do not edit.",
         "// NCT marks inlined as data URIs (artifact CSP blocks external images).", ""]
total = 0
for name, fname, w, grad in ITEMS:
    b64, size, raw = encode(os.path.join(SRC, fname), w, grad)
    total += len(b64)
    lines.append("/** %s - %dx%d, %.1f KB */" % (fname, size[0], size[1], raw / 1024))
    # `: string` stops TS inferring a literal type - without it tsup copies the
    # whole base64 blob into index.d.ts as well as index.js
    lines.append("export const %s: string = 'data:image/png;base64,%s';" % (name, b64))
    lines.append("")
    print("  %-11s %4dx%-4d %7.1f KB raw" % (name, size[0], size[1], raw / 1024))

for name, fname, mime in PHOTOS:
    raw = open(os.path.join(SRC, fname), "rb").read()
    b64 = base64.b64encode(raw).decode("ascii")
    total += len(b64)
    size = Image.open(os.path.join(SRC, fname)).size
    lines.append("/** %s - %dx%d, %.1f KB */" % (fname, size[0], size[1], len(raw) / 1024))
    lines.append("export const %s: string = 'data:%s;base64,%s';" % (name, mime, b64))
    lines.append("")
    print("  %-11s %4dx%-4d %7.1f KB raw" % (name, size[0], size[1], len(raw) / 1024))

# The corp cover's decorative column. One hue at many alphas, so it is an SVG
# built from tokens.COVER_SCATTER rather than the source deck's 472x1080 PNG -
# same artwork, ~1 KB instead of ~40, and it recolours with the token.
import tokens as T                                          # noqa: E402

_sw, _sh = T.COVER_SCAT_BOX
_rects = "".join(
    '<rect x="%d" y="%d" width="%d" height="%d" fill="%%23%s" fill-opacity="%.2f"/>'
    % (x, y, w, h, T.MID, a / 100.0)
    for x, y, w, h, a in T.COVER_SCATTER)
_svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
        'preserveAspectRatio="none">%s</svg>' % (_sw, _sh, _rects))
lines.append("/** corp cover scatter - %d squares of MID, generated from "
             "tokens.COVER_SCATTER */" % len(T.COVER_SCATTER))
lines.append("export const coverScatter: string = "
             "'data:image/svg+xml,%s';" % _svg.replace("'", "%27"))
lines.append("")
print("  %-11s %4dx%-4d %7.1f KB raw" % ("coverScatter", _sw, _sh, len(_svg) / 1024))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("\nweb/src/assets.ts  %.1f KB of base64" % (total / 1024))
