// Emits the Claude Design port of <Icon> from the one list of glyphs @nct/slides
// ships - the lucide re-export block in web/src/index.ts:
//   components/icons/Icon.jsx        path data inlined (a design there has no npm)
//   components/icons/Icon.d.ts       the glyph names as a string union
//   components/icons/Icon.prompt.md  the rules and the list, for the design agent
//   components/icons/card.html       the Design System card, sized to the list
// then renders every glyph once as a self-check. Upload the four files with
// DesignSync; the project's _ds_bundle.js / _ds_manifest.json still need Icon.jsx
// compiled in (see .design-sync/NOTES.md).
//
// usage: node scripts/emit_design_icons.mjs <out dir>
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = process.argv[2];
if (!outDir) {
  console.error("usage: node scripts/emit_design_icons.mjs <out dir>");
  process.exit(2);
}
const fail = (msg) => {
  console.error(`FAIL: ${msg}`);
  process.exit(1);
};

const lucideDir = path.join(repo, "node_modules/lucide-react");
const iconsDir = path.join(lucideDir, "dist/esm/icons");
const lucideVersion = JSON.parse(fs.readFileSync(path.join(lucideDir, "package.json"), "utf8")).version;

// ---- the list
const entry = fs.readFileSync(path.join(repo, "web/src/index.ts"), "utf8");
const block = entry.match(/export\s*\{([^}]*)\}\s*from\s*"lucide-react"/);
if (!block) fail('no `export { ... } from "lucide-react"` block in web/src/index.ts');
const NAMES = block[1].split(",").map((s) => s.trim()).filter(Boolean);
if (!NAMES.every((n) => /^[A-Z][A-Za-z0-9]*$/.test(n))) fail("the lucide block holds something that is not a glyph name");
if (new Set(NAMES).size !== NAMES.length) fail("a glyph is listed twice in web/src/index.ts");

// ---- name -> icon module. lucide's own entry says which file an export comes from;
// kebab-case of the name is the fallback.
const kebab = (n) => n.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([a-zA-Z])(\d)/g, "$1-$2").toLowerCase();
const lucideEntry = fs.readFileSync(path.join(lucideDir, "dist/esm/lucide-react.mjs"), "utf8");
function moduleFor(name) {
  const m = lucideEntry.match(new RegExp(`default as ${name}\\b[^}]*\\}\\s*from\\s*["']\\./icons/([\\w-]+)\\.mjs["']`));
  const file = path.join(iconsDir, `${m ? m[1] : kebab(name)}.mjs`);
  if (!fs.existsSync(file)) fail(`${name}: no icon module (looked for ${path.basename(file)})`);
  return file;
}

// lucide-react 1.x exports each glyph as `__iconData = { name, size, node }`; old names
// are alias modules (`export { default } from './x.mjs'`) with no data of their own.
async function iconNode(file, depth = 0) {
  const { __iconData } = await import(pathToFileURL(file).href);
  if (__iconData) {
    if (!__iconData.node || __iconData.size !== 24) fail(`unexpected icon data in ${file}`);
    return __iconData.node;
  }
  const alias = fs.readFileSync(file, "utf8").match(/export\s*\{\s*default\s*\}\s*from\s*["']\.\/([\w-]+)\.mjs["']/);
  if (!alias || depth > 2) fail(`no __iconData and no alias in ${file}`);
  return iconNode(path.join(iconsDir, `${alias[1]}.mjs`), depth + 1);
}

const glyphs = {};
for (const name of NAMES) {
  // lucide adds a React `key` to every child; the component supplies its own
  glyphs[name] = (await iconNode(moduleFor(name))).map(([tag, { key, ...attrs }]) => [tag, attrs]);
}

// ---- Icon.jsx
const jsx = `import React from "react";

/* The lucide glyphs @nct/slides ships (web/src/index.ts), as lucide's own 24x24 path
   data - lucide-react ${lucideVersion}, ISC licence (lucide.dev/license). Generated by
   scripts/emit_design_icons.mjs; inlined because a design here has no npm. */
const GLYPHS = {
${NAMES.map((n) => `  ${n}: ${JSON.stringify(glyphs[n])},`).join("\n")}
};

/* --nct-heading and --nct-on-dark-1 are upstream tokens this project has not ported
   yet; the fallbacks are what they resolve to in the web brand today. */
const TONE = {
  accent: "var(--nct-accent)",
  "accent-up": "var(--nct-accent-up)",
  heading: "var(--nct-heading, var(--nct-navy))",
  "ink-2": "var(--nct-ink-2)",
  "on-dark": "var(--nct-on-dark-1, var(--nct-paper))",
};

const kebab = (n) => n.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([a-zA-Z])(\\d)/g, "$1-$2").toLowerCase();

/**
 * A lucide glyph sized to a type token and coloured by a role token, so an icon is
 * set like a word, not placed like a picture. It sits beside words and never
 * replaces them.
 */
export function Icon({ icon, size, tone, label }) {
  const node = GLYPHS[icon];
  if (!node) {
    console.warn(\`<Icon>: "\${icon}" is not one of the glyphs in Icon.prompt.md\`);
    return null;
  }
  return React.createElement(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      width: "1em",
      height: "1em",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: 2,
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: \`lucide lucide-\${kebab(icon)}\`,
      ...(label ? { role: "img", "aria-label": label } : { "aria-hidden": "true" }),
      style: {
        fontSize: size && \`var(--nct-fs-\${size})\`,
        color: tone && TONE[tone],
        verticalAlign: "-0.125em",
        flexShrink: 0,
      },
    },
    node.map(([tag, attrs], i) => React.createElement(tag, { ...attrs, key: i }))
  );
}
`;

// ---- Icon.d.ts
const union = [];
for (let i = 0; i < NAMES.length; i += 6) union.push(NAMES.slice(i, i + 6).map((n) => `"${n}"`).join(" | "));
const dts = `export type IconGlyph =
  | ${union.join("\n  | ")};

export interface IconProps {
  /** One of the glyphs in Icon.prompt.md, by name. Anything else renders nothing and warns. */
  icon: IconGlyph;
  /** The type step it sits beside. Omit and it matches the surrounding text (1em). */
  size?: "stat" | "h1" | "lead" | "body" | "body-2" | "body-3" | "label" | "densehead" | "densebody";
  /**
   * Omit to inherit the text colour. \`accent\` on paper, \`accent-up\` on \`--nct-dark\` -
   * the same pair rule as text. No status or category tones: those are data.
   */
  tone?: "accent" | "accent-up" | "heading" | "ink-2" | "on-dark";
  /** Names the icon for screen readers. Omit when the words beside it already say it. */
  label?: string;
}

/**
 * A lucide glyph sized to a type token and coloured by a role token, so an icon is
 * set like a word, not placed like a picture. The stroke scales with the size the
 * way a font's weight does. An icon sits beside words and never replaces them.
 */
export function Icon(props: IconProps): JSX.Element | null;
`;

// ---- Icon.prompt.md
const prompt = `One lucide glyph, set like a word: \`size\` is a \`--nct-fs-*\` step and \`tone\` a role token; omit both and it follows the text around it. The glyph is named by string and must be one of these — anything else renders nothing:

${NAMES.map((n) => `\`${n}\``).join(" ")}

Pick the nearest one; never draw an SVG by hand or pull in another icon set. An icon sits beside words, never instead of them — no icon-only cards, no centred icon grid, no icons inside \`DiagramBox\`. \`accent\` on paper, \`accent-up\` on a dark panel. Add \`label\` only when no words beside it say the same thing.

\`\`\`jsx
<h3 className="nct-card__heading">
  <Icon icon="ShieldCheck" tone="accent" /> ตรวจสอบได้
</h3>
<p style={{ fontSize: "var(--nct-fs-densebody)" }}>
  <Icon icon="Clock" tone="ink-2" /> ปิดงบภายใน 2 วันทำการ
</p>
\`\`\`
`;

// ---- card.html: two sample lines, then the glyphs by name in four columns
const COLS = 4;
const ROW_H = 27; // a densehead glyph plus the 6px row gap
const cardHeight = Math.ceil((150 + Math.ceil(NAMES.length / COLS) * ROW_H) / 10) * 10;
const card = `<!-- @dsCard group="Components" viewport="760x${cardHeight}" name="Icon" subtitle="Lucide glyphs, sized by type token and coloured by role — always beside words" -->
<html><head><link rel="stylesheet" href="../../styles.css">
<script src="https://unpkg.com/react@18.3.1/umd/react.development.js" integrity="sha384-hD6/rw4ppMLGNu3tX5cjIb+uRZ7UkRJ6BPkLpg4hAu/6onKUg4lLsHAs9EBPT82L" crossorigin="anonymous"></script>
<script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.development.js" integrity="sha384-u6aeetuaXnQ38mYT8rp6sbXaQe3NL9t+IBXmnYxwkUI2Hw4bsp2Wvmx4yRQF1uAm" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@babel/standalone@7.29.0/babel.min.js" integrity="sha384-m08KidiNqLdpJqLq95G/LEi8Qvjl/xUYll3QILypMoQ65QorJ9Lvtp2RXYGBFj1y" crossorigin="anonymous"></script>
<script src="../../_ds_bundle.js"></script>
</head><body style="margin:0;padding:16px;background:#fff;font-family:var(--nct-font-body);color:var(--nct-ink)">
<div id="root"></div>
<script type="text/babel">
const { Icon } = window.NCTDesignSystem_7648d8;
const GLYPHS = ${JSON.stringify(NAMES)};
function App(){return (
<>
<p style={{margin:"0 0 6px",fontFamily:"var(--nct-font-display)",fontWeight:700,fontSize:"var(--nct-fs-densehead)",color:"var(--nct-heading, var(--nct-navy))"}}>
  <Icon icon="ShieldCheck" tone="accent" /> ตรวจสอบได้
</p>
<p style={{margin:"0 0 14px",fontSize:"var(--nct-fs-densebody)",color:"var(--nct-ink-2)"}}>
  <Icon icon="Clock" /> ปิดงบภายใน 2 วันทำการ — icon เท่าตัวอักษร สีตาม role token
</p>
<ul style={{listStyle:"none",margin:0,padding:"12px 0 0",borderTop:"1px solid var(--nct-rule)",display:"grid",gridTemplateColumns:"repeat(${COLS}, 1fr)",rowGap:6,columnGap:12,fontSize:"var(--nct-fs-densecell)"}}>
  {GLYPHS.map(g => (
    <li key={g} style={{display:"flex",alignItems:"center",gap:8}}>
      <Icon icon={g} size="densehead" tone="accent" />
      <span>{g}</span>
    </li>
  ))}
</ul>
</>
);}
ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
</script>
</body></html>
`;

const iconDir = path.join(outDir, "components/icons");
fs.mkdirSync(iconDir, { recursive: true });
fs.writeFileSync(path.join(iconDir, "Icon.jsx"), jsx);
fs.writeFileSync(path.join(iconDir, "Icon.d.ts"), dts);
fs.writeFileSync(path.join(iconDir, "Icon.prompt.md"), prompt);
fs.writeFileSync(path.join(iconDir, "card.html"), card);

// ---- self-check: load Icon.jsx the way the bundle does (React as a global binding,
// import line and export keyword stripped), render every glyph, then compare each
// against the lucide-react component @nct/slides ships
const require = createRequire(path.join(repo, "web/package.json"));
const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const body = jsx.replace(/^import React from "react";\n/, "").replace(/^export function/m, "function");
const Icon = Function("React", `${body}\nreturn Icon;`)(React);
const lucideReact = require("lucide-react");
const inner = (html) => html.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");

for (const name of NAMES) {
  const ours = renderToStaticMarkup(React.createElement(Icon, { icon: name, size: "body", tone: "accent" }));
  if (!/^<svg[^>]*viewBox="0 0 24 24"/.test(ours)) fail(`${name} did not render an svg`);
  if (typeof lucideReact[name] !== "object" && typeof lucideReact[name] !== "function") fail(`lucide-react has no export ${name}`);
  if (inner(ours) !== inner(renderToStaticMarkup(React.createElement(lucideReact[name])))) fail(`${name} differs from lucide-react's own glyph`);
}
const labelled = renderToStaticMarkup(React.createElement(Icon, { icon: NAMES[0], label: "ป้าย" }));
if (!labelled.includes('role="img"') || !labelled.includes('aria-label="ป้าย"')) fail("label did not reach the svg");
const warn = console.warn;
let warned = false;
console.warn = () => { warned = true; };
const unknown = renderToStaticMarkup(React.createElement(Icon, { icon: "NotAGlyph" }));
console.warn = warn;
if (unknown !== "" || !warned) fail("an unknown glyph should render nothing and warn");

console.log(`${NAMES.length} glyphs from web/src/index.ts, lucide-react ${lucideVersion}`);
console.log(`wrote ${iconDir}: Icon.jsx (${jsx.length} bytes), Icon.d.ts, Icon.prompt.md, card.html (760x${cardHeight})`);
console.log("every glyph matches lucide-react's own render; label and unknown-name checks pass");
