# -*- coding: utf-8 -*-
"""Emit web/src/tokens.css + tokens.ts from scripts/tokens.py.

tokens.py stays the single source of truth for BOTH outputs (the .potx and the
React package). Never hand-edit the generated files - change tokens.py and rerun.
"""
import os
import tokens as T

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(os.path.dirname(HERE), "web", "src")

EMU_IN = 914400.0
PX_IN = 96.0            # slide canvas renders at 96dpi -> 1280 x 720 px


def px(emu):
    """EMU -> px, rounded to 0.01 so the web canvas matches the .potx geometry"""
    return round(emu / EMU_IN * PX_IN, 2)


COLORS = [
    ("paper", T.PAPER, "page background"),
    ("paper-2", T.PAPER2, "tinted surface: cards, quote slide"),
    ("ink", T.INK, "body text"),
    ("ink-2", T.INK2, "caption, label, footer"),
    ("rule", T.RULE, "hairline, divider"),
    ("navy", T.NAVY, "headings, dark panels, primary accent"),
    ("teal", T.TEAL, "rules, bullets, links, secondary accent"),
    ("teal-l", T.TEAL_L, "section numbers on dark, 2nd chart series"),
    ("deep", T.DEEP, "photo scrim, full-image background"),
    ("mid", T.MID, "gradient midpoint (L01 / L10) - gradient stop only"),
    ("teal-b", T.TEAL_B, "gradient END stop only - never fill/line/text (fails AA)"),
    ("risk", T.RISK, "status: blocker (table / process cells only)"),
    ("risk-tint", T.RISK_T, "status fill behind --nct-risk"),
    ("warn", T.WARN, "status: unconfirmed / needs decision"),
    ("warn-tint", T.WARN_T, "status fill behind --nct-warn"),
    ("ok", T.OK, "status: ready / passed"),
    ("ok-tint", T.OK_T, "status fill behind --nct-ok"),
    ("cat-1", T.CAT_1, "category coding 1 of 4 - reuses navy"),
    ("cat-2", T.CAT_2, "category coding 2 of 4 - reuses teal"),
    ("cat-3", T.CAT_3, "category coding 3 of 4 - reuses teal-l"),
    ("cat-4", T.CAT_4, "category coding 4 of 4 - reuses deep"),
]

SPACE = [
    ("slide-w", T.SW), ("slide-h", T.SH),
    ("mx", T.MX), ("mt", T.MT), ("mb", T.MB),
    ("cw", T.CW), ("gut", T.GUT), ("col", T.COL),
    ("half", T.HALF), ("third", T.THIRD),
    ("quarter", T.QUARTER), ("fifth", T.FIFTH),
    ("title-y", T.TITLE_Y), ("title-h", T.TITLE_H),
    ("rule-y", T.RULE_Y), ("rule-h", T.RULE_H), ("rule-w", T.RULE_W),
    ("body-y", T.BODY_Y), ("body-h", T.BODY_H),
]

TYPE = [
    ("display", T.T_DISPLAY, "title slide"),
    ("section", T.T_SECTION, "section divider title"),
    ("h1", T.T_H1, "slide title"),
    ("stat", T.T_STAT, "big figure"),
    ("quote", T.T_QUOTE, "pull quote"),
    ("lead", T.T_LEAD, "subtitle / panel kicker"),
    ("body", T.T_BODY, "body level 1"),
    ("body-2", T.T_BODY2, "body level 2"),
    ("body-3", T.T_BODY3, "body level 3 / caption"),
    ("label", T.T_LABEL, "eyebrow / stat label"),
    ("foot", T.T_FOOT, "footer, page number"),
    ("stepnum", T.T_STEPNUM, "dense: step / card number"),
    ("densehead", T.T_DENSEHEAD, "dense: section heading (L11-L14)"),
    ("densebody", T.T_DENSEBODY, "dense: body copy (L11-L14)"),
    ("tblhead", T.T_TBLHEAD, "dense: table header (L16)"),
    ("densecell", T.T_DENSECELL, "dense: table cell (L16) - 10pt floor"),
]

HEADER = ("/* Generated by scripts/emit_web_tokens.py from scripts/tokens.py.\n"
          "   Do not edit - change tokens.py and rerun. */\n")


def css():
    out = [HEADER, ":root {"]
    out.append("  /* ---- colour ---- */")
    for name, hexv, note in COLORS:
        out.append("  --nct-%-12s #%s;%s" % (name + ":", hexv, "  /* %s */" % note))
    out.append("")
    out.append("  /* ---- canvas & grid (px at 96dpi; 1px = 9525 EMU) ---- */")
    for name, emu in SPACE:
        out.append("  --nct-%-12s %gpx;" % (name + ":", px(emu)))
    out.append("")
    out.append("  /* ---- type scale (pt in the deck, px here) ---- */")
    for name, hpt, note in TYPE:
        out.append("  --nct-fs-%-10s %gpx;  /* %gpt - %s */"
                   % (name + ":", round(hpt / 100 * PX_IN / 72, 2), hpt / 100, note))
    out.append("")
    out.append("  /* ---- families: Kanit is the heading voice, Noto the body voice ---- */")
    out.append("  --nct-font-display: 'Kanit', 'Noto Sans Thai', system-ui, sans-serif;")
    out.append("  --nct-font-body: 'Noto Sans Thai', 'Kanit', system-ui, sans-serif;")
    out.append("")
    out.append("  /* ---- gradients: L01 opens navy->teal, L10 closes teal->navy ---- */")
    out.append("  --nct-grad-open: linear-gradient(135deg, #%s 0%%, #%s 55%%, #%s 100%%);"
               % (T.NAVY, T.MID, T.TEAL))
    out.append("  --nct-grad-close: linear-gradient(135deg, #%s 0%%, #%s 55%%, #%s 100%%);"
               % (T.TEAL, T.MID, T.NAVY))
    out.append("  --nct-scrim: linear-gradient(to bottom, transparent 0%%, "
               "#%s99 55%%, #%se6 100%%);" % (T.DEEP, T.DEEP))
    out.append("}")
    return "\n".join(out) + "\n"


def ts():
    out = [HEADER.replace("/*", "//").replace("*/", "").replace("\n   ", "\n// ").rstrip(),
           "", "export const color = {"]
    for name, hexv, note in COLORS:
        out.append("  %s: '#%s'," % (name.replace("-", "_"), hexv))
    out.append("} as const;")
    out.append("")
    out.append("/** slide canvas in px at 96dpi - the .potx is 13.333in x 7.5in */")
    out.append("export const canvas = { width: %g, height: %g } as const;"
               % (px(T.SW), px(T.SH)))
    out.append("")
    out.append("export const space = {")
    for name, emu in SPACE:
        out.append("  %s: %g," % (name.replace("-", "_"), px(emu)))
    out.append("} as const;")
    out.append("")
    out.append("export const fontSize = {")
    for name, hpt, note in TYPE:
        out.append("  %s: %g," % (name.replace("-", "_"),
                                  round(hpt / 100 * PX_IN / 72, 2)))
    out.append("} as const;")
    out.append("")
    out.append("export type NctColor = keyof typeof color;")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    os.makedirs(WEB, exist_ok=True)
    for name, body in (("tokens.css", css()), ("tokens.ts", ts())):
        with open(os.path.join(WEB, name), "w", encoding="utf-8") as f:
            f.write(body)
        print("wrote web/src/%s (%d bytes)" % (name, len(body)))
