// Generated by scripts/emit_web_tokens.py from scripts/tokens.py.
// Do not edit - change tokens.py and rerun.

export const color = {
  paper: '#FFFFFF',
  paper_2: '#E8F6F5',
  ink: '#333333',
  ink_2: '#5F5F5F',
  rule: '#E5E5E5',
  navy: '#23436D',
  teal: '#216B7F',
  teal_l: '#4E8FA8',
  teal_up: '#8FBACE',
  deep: '#16324F',
  mid: '#1E5473',
  teal_b: '#1A8D92',
  risk: '#B3261E',
  risk_tint: '#F6D0CC',
  warn: '#7F4B00',
  warn_tint: '#F2D9AC',
  ok: '#1A6647',
  ok_tint: '#BFE3CA',
  cat_1: '#23436D',
  cat_2: '#216B7F',
  cat_3: '#4E8FA8',
  cat_4: '#16324F',
} as const;

/** slide canvas in px at 96dpi - the .potx is 13.333in x 7.5in */
export const canvas = { width: 1280, height: 720 } as const;

export const space = {
  slide_w: 1280,
  slide_h: 720,
  mx: 96,
  mt: 57.6,
  mb: 57.6,
  cw: 1088,
  gut: 19.2,
  col: 73.07,
  half: 534.4,
  third: 349.87,
  quarter: 257.6,
  fifth: 202.24,
  band_w: 512,
  band_text_w: 652.8,
  title_y: 57.6,
  title_h: 76.8,
  rule_y: 144,
  rule_h: 4.8,
  rule_w: 57.6,
  body_y: 177.6,
  body_h: 456,
  take_h: 43.2,
  note_h: 28.8,
  note_up: 52.8,
} as const;

export const fontSize = {
  display: 58.67,
  section: 53.33,
  h1: 42.67,
  stat: 96,
  quote: 37.33,
  lead: 26.67,
  body: 24,
  body_2: 21.33,
  body_3: 18.67,
  label: 16,
  foot: 13.33,
  stepnum: 32,
  densehead: 21.33,
  densebody: 16,
  tblhead: 14.67,
  densecell: 13.33,
} as const;

export type NctColor = keyof typeof color;
